import type { HeroSlide } from '../components/HeroCarousel';
import type { Work } from '../components/WorksGrid';

// ── Hero Carousel slides (5) ──────────────────────────────────
export const HERO_SLIDES: HeroSlide[] = [
  {
    img: '/images/hero/hero-slide-1.jpg',
    alt: '綿甜體字樣特寫',
    eyebrow: 'Shenghe Design Studio',
    title: '設計，是溝通的最短距離',
    titleAccent: '溝通',
    subtitle: '專注品牌識別、字體排版與文化視覺設計。從企業品牌到政府標案，讓你的形象說話。',
  },
  {
    img: '/images/hero/hero-slide-2.jpg',
    alt: '品牌識別系統展示',
    eyebrow: 'Brand Identity · Typography',
    title: '從策略到視覺，一步到位',
    titleAccent: '一步到位',
    subtitle: '深耕平面設計逾十年，為每位客戶量身打造具備說服力的品牌視覺系統。',
  },
  {
    img: '/images/hero/hero-slide-3.jpg',
    alt: '書法筆觸與數位字型對照',
    eyebrow: 'Editorial Design · Exhibition',
    title: '讓好設計，說好的故事',
    titleAccent: '好的故事',
    subtitle: '書籍裝幀、年報排版、展覽主視覺——細節決定質感，質感塑造信任。',
  },
  {
    img: '/images/hero/hero-slide-4.svg',
    alt: '包裝設計作品',
    eyebrow: 'Packaging · Print Collateral',
    title: '細節裡的品牌溫度',
    titleAccent: '品牌溫度',
    subtitle: '從禮盒結構到陳列展示架，每一處觸點都是品牌印象的延伸。',
  },
  {
    img: '/images/hero/hero-slide-5.svg',
    alt: '字體規格系統',
    eyebrow: 'fontsfun · Type System',
    title: '一套字型，六種表情',
    titleAccent: '六種表情',
    subtitle: '綿甜體六字重系統——柔、光、霜、潤、醇、蜜，從標題到內文一氣呵成。',
  },
];

// ── Portfolio works (16) ──────────────────────────────────────
export const WORKS: Work[] = [
  { cat: 'brand', workCat: 'Brand Visual', titleEn: 'Cloud Bookfont',
    title: '字趣 雲書體 主視覺',
    desc: '字趣 fontsfun 2025 年度新作「雲書體」發表主視覺。以青空、雲形、墨痕構成飄逸書寫意象，強調「圓潤筆觸 · 現代優雅」的字型氣質。',
    result: '2025 年度新字型發表＋早鳥試用活動視覺',
    img: '/images/works/brand/fontsfun-cloudbook.jpg',
    alt: '字趣 雲書體 字型發表主視覺' },

  { cat: 'editorial', workCat: 'Book Cover', titleEn: 'Joseph de Prémare',
    title: '馬若瑟的文學世界',
    desc: '臺大出版中心《臺大哈佛燕京學術叢書 13》。書封以馬若瑟手稿原跡為視覺主軸，疊合書名印章，呈現古典文獻的學術質感。',
    result: '臺大出版中心 學術叢書裝幀設計',
    img: '/images/works/editorial/book-joseph-premare.jpg',
    alt: '馬若瑟的文學世界 書封' },

  { cat: 'brand', workCat: 'OOH Campaign', titleEn: 'Lunar Greeting Bus',
    title: '正官庄 蔘享新年公車',
    desc: '正官庄「蔘享新年・臺品之選深意極現」公車車體廣告 KV。整合品牌代言人許光漢形象、產品全系列陳列、新春節慶氛圍，於大南汽車 085-FR 車線曝光。',
    result: '代言人 KV ＋全產品線車體廣告整合',
    img: '/images/works/brand/chkj-bus-ad.jpg',
    alt: '正官庄 公車車體廣告' },

  { cat: 'editorial', workCat: 'Book Cover', titleEn: 'Tranquil Distance',
    title: '寧靜致遠',
    desc: 'Sunny 文庫 265《富蘭克林的人生守則》。封面以暖色插畫描繪冥想場景，搭配手寫風書名，呼應「品格高尚是一生的財富」的閱讀主題。',
    result: 'Sunny 文庫 富蘭克林人生守則 書封',
    img: '/images/works/editorial/book-tranquil-distance.jpg',
    alt: '寧靜致遠 書封設計' },

  { cat: 'packaging', workCat: 'Packaging Design', titleEn: 'Ginseng Milk Tea',
    title: '正官庄 × 3點1刻 高麗蔘奶茶',
    desc: '跨品牌聯名包裝設計。以「遊客必買伴手禮」為主訴求，融合臺灣黑熊插畫、紅金主視覺與韓文標題，鎖定來臺觀光客伴手禮市場。',
    result: '高麗蔘奶茶聯名禮盒包裝設計',
    img: '/images/works/packaging/chkj-3pm-milktea.jpg',
    alt: '正官庄 × 3點1刻 高麗蔘奶茶聯名包裝' },

  { cat: 'brand', workCat: 'Key Visual', titleEn: 'Everytime',
    title: '正官庄 EVERYTIME',
    desc: '高麗蔘精 EVERYTIME 系列主視覺。以「提升保護力」為標語訴求，紅綠對比配色搭配人蔘原料插畫，建立輕巧包裝、即撕即飲的清新印象。',
    result: '高麗蔘精系列主視覺與包裝海報',
    img: '/images/works/brand/chkj-everytime-poster.jpg',
    alt: '正官庄 EVERYTIME 主視覺海報' },

  { cat: 'editorial', workCat: 'Book Cover', titleEn: 'Women & National Trauma',
    title: '明清文學中的女子與國難',
    desc: '臺大出版中心《中國文學研究叢書 16》。以明清文人線描仕女圖搭配深藍主色，呼應書名「女子與國難」的歷史厚度與文學批判視角。',
    result: '臺大出版中心 學術叢書設計',
    img: '/images/works/editorial/book-ming-qing-women.jpg',
    alt: '明清文學中的女子與國難 書封' },

  { cat: 'brand', workCat: 'Promo Campaign', titleEn: 'Flash Sale Day',
    title: '正官庄 破盤日 KV',
    desc: '夏季「破盤日 7.1–7.31」季節促銷主視覺。以紅色爆破字體、立體浮雕標題搭配代言人實拍，建立超殺折扣的視覺張力，整合 9 款主打商品價格資訊。',
    result: '季節促銷主視覺＋商品 DM 整合',
    img: '/images/works/brand/chkj-flash-sale-dm.jpg',
    alt: '正官庄 破盤日 DM' },

  { cat: 'type', workCat: 'Character Design', titleEn: 'Cookie Expressions',
    title: '餅乾人 字符組',
    desc: '40 款表情字符組（character set）設計，以擬人化餅乾為造型主體，每一格細節豐富刻畫情緒：開心／驚訝／無奈／害羞⋯⋯適用於通訊貼圖與品牌 IP 衍伸。',
    result: '40 款擬人化表情貼圖字符設計',
    img: '/images/works/type/cookie-character-set.jpg',
    alt: '餅乾人 40 款表情字符組' },

  { cat: 'editorial', workCat: 'Book Cover', titleEn: 'Lonely Boat Inquiry',
    title: '寂寞舟中誰借問',
    desc: 'Sara 文庫 268《我們的「人之初」為誰殉葬》。封面以水墨潑灑的孤舟少年背影為主視覺，深藍冷色調呼應「再尋一代少年背影」的詩意主題。',
    result: 'Sara 文庫 詩集裝幀設計',
    img: '/images/works/editorial/book-lonely-boat.jpg',
    alt: '寂寞舟中誰借問 書封' },

  { cat: 'editorial', workCat: 'Event Visual', titleEn: 'Thank You Campaign',
    title: '正官庄 感謝有您',
    desc: '正官庄會員回饋活動視覺。粉綠雙色塊配色搭配代言人李敏鎬實拍，傳達「與正官庄勇往直前」的品牌承諾，含限量 120 盒早鳥優惠資訊。',
    result: '會員回饋活動視覺＋優惠資訊整合',
    img: '/images/works/editorial/chkj-thanks-poster.jpg',
    alt: '正官庄 感謝有您 海報' },

  { cat: 'brand', workCat: 'Promo Campaign', titleEn: 'Anniversary Sale',
    title: '正官庄 周年慶 KV',
    desc: '正官庄年度週年慶主視覺。金黃節慶配色搭配「年末最強特惠組」標題，整合多檔商品優惠（活蔘 28D PLUS / 高麗蔘雞精 / EVERYTIME PLUS）的完整 DM 設計。',
    result: '週年慶主視覺＋商品優惠 DM 設計',
    img: '/images/works/brand/chkj-anniversary-dm.jpg',
    alt: '正官庄 周年慶 DM' },

  { cat: 'brand', workCat: 'Brand Concept', titleEn: 'The Idea Collective',
    title: 'IDEA 創意團隊概念視覺',
    desc: '創意團隊形象概念照。俯拍視角呈現多人協作的工作桌面，融合手繪 IDEA 字樣、色票、手稿、平板、咖啡與多元雙手，傳達跨領域協作的創意能量。',
    result: '創意團隊形象與品牌概念視覺',
    img: '/images/works/brand/idea-team.jpg',
    alt: 'IDEA 創意團隊概念照' },

  { cat: 'packaging', workCat: 'Print Collateral', titleEn: 'Lottery Ticket',
    title: '正官庄 抽獎券',
    desc: '正官庄健康蔘級「消費抽好禮」紙本抽獎券設計。18.7 × 8.2 cm 雙聯式票券，含流水號區、撕線、店家聯回收聯，整合 iPhone 13 抽獎活動視覺與使用說明。',
    result: '雙聯式抽獎券＋活動辦法整合設計',
    img: '/images/works/packaging/chkj-lottery-ticket.jpg',
    alt: '正官庄 抽獎券' },

  { cat: 'packaging', workCat: 'Print Collateral', titleEn: 'Anniversary Flyer',
    title: '正官庄 周年慶傳單',
    desc: '正官庄週年慶實體傳單設計。10.12–11.8 限定回饋上市，整合 AirPods Pro 滿額贈、Dyson 高額贈與兒童保健精選商品，主打「滿 6000 現折 600」優惠機制。',
    result: '週年慶 DM 傳單＋滿額贈機制視覺',
    img: '/images/works/packaging/chkj-anniversary-flyer.jpg',
    alt: '正官庄 周年慶傳單' },

  { cat: 'type', workCat: 'Character Design', titleEn: 'Koala Stickers',
    title: '無尾熊 字符組',
    desc: '原創 IP 角色字符設計。以橘色無尾熊為造型主體，繪製揮手「88～」、痛哭、開心三款核心情緒表情，可延伸至貼圖系列與品牌吉祥物應用。',
    result: '原創 IP 無尾熊角色設計',
    img: '/images/works/type/koala-character-set.jpg',
    alt: '無尾熊 字符組' },
];
